[IN-49]: initial commit
w3w-internal/bigcommerce-storefront-plugin pull request #1
Opened 2022-11-23 12:24 UTC by electather

# Description

## What is the motivation for this pull request?

## What is the solution?

## What areas of the site does it impact?

## How to test?

- [ ] Test A
- [ ] Test B

## Other Notes

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-11-24 14:07 UTC, electather commented
Found an issue with the current implementation. 
bigcommerce calls the consignments patch call with every field, so the in-memory value of “address line 2” is sent. after the user fills any field

2022-11-25 11:43 UTC, electather commented on src/index.ts
> +  };
Used during development. should be replaced with `{}` once we hit V1.

2022-11-28 12:14 UTC, c5haw requested changes

2022-11-28 12:14 UTC, c5haw commented on package.json
> +    "pattern": "^main$|^(IN|in)()(-\\d+)(-[a-z-]+)?$",
```suggestion
    "pattern": "^main$|^(TT|IN|DEV)-\\d+(-[a-z0-9-]+)?$",
```
This allows tickets in any project to create branches and make changes without having to keep changing this in every project. Also I'd like to keep some consistency here rather than each individual project having different regex. Happy to make changes to it, but I'd prefer it go through ADR, agree by the team and rolled out everywhere including the boilerplate.

2022-11-28 12:25 UTC, c5haw requested changes
Would be great to get some tests written here and get a good 90% coverage here before we merge this. I think it's important that we establish test coverage for anything new from the offset and that it should be quite exhaustive and include Pact as much as possible.

2022-11-28 12:25 UTC, c5haw commented on package.json
> +    "build": "VERSION=$npm_package_version webpack --config webpack.prod.js",
Should this not just override `compile` which is no longer `tsc`?

2022-11-28 12:25 UTC, c5haw commented on src/components/auto-suggest.ts
> +        [`BigCommerce`].join(' ') +
We could try to embed some more metadata here like [WordPress](https://github.com/what3words/wordpress-autosuggest-plugin/blob/master/w3w-autosuggest/public/js/w3w-autosuggest-public.js#L435)

2022-11-28 14:55 UTC, electather commented on src/components/auto-suggest.ts
> +        [`BigCommerce`].join(' ') +
couldn't find anything useful. kept the array in case we do find something usefull to add in the future.

2022-11-28 15:02 UTC, electather commented on package.json
> +    "build": "VERSION=$npm_package_version webpack --config webpack.prod.js",
just following the same structure I laid down for ecwid.
not a strong reason for keeping `tsc`, but it can be used as a lighter version of static type checking without running heavier webpack.

2022-11-28 15:04 UTC, electather commented
> include Pact as much as possible.
@c5haw we don't have any network requests here. I'm working on adding unit tests IN-119, since IN-115 and IN-116 both add some changes to w3w mount function.

2022-11-29 09:33 UTC, imndaiga commented on .vscode/settings.json
> +  "cSpell.words": ["bigcommerce"]
Looks like `precoverage` and `pretest` aren't recognised by cSpell, should add here

2022-11-29 10:21 UTC, electather commented on .vscode/settings.json
> +  "cSpell.words": ["bigcommerce"]
```suggestion
  "cSpell.words": ["bigcommerce", "precoverage", "pretest"]
```

2022-11-29 10:32 UTC, imndaiga commented on src/components/auto-suggest.ts
> +function createAutosuggestComponent(config: PluginSettings, props: Props = {}) {
Two comments:
 - We should likely specify the return type here
 - For simple type definitions, would it not be better to have them inline?
 - Probably scope creep (+ I'm not sure what pattern we prefer), but would we want to have some custom prop passing capability here?

The above could perhaps take the following form
```js
  function createAutosuggestComponent(
    config: PluginSettings,
    props: {
      defaultLanguage?: string;
      custom?: {}
    } = {}
  ): HTMLElement {
    const w3wComponent = document.createElement('what3words-autosuggest');
    const customPropEntries = Object.entries(props?.custom || {});
    if (customPropEntries.length) {
        customPropEntries.forEach(propEntry => {
            if (/\W/g.test(propEntry?.[0])) { // regex would need a sanity check
              throw new Error("Invalid HTML property name given. Cannot contain special characters except '_'".);
            }
            w3wComponent.setAttribute(...propEntry);
        });
    }
    ... // controlled attribute setting logic goes here to override any set by custom logic above
  }
```

2022-11-29 12:00 UTC, imndaiga commented on src/components/mount-auto-suggest.ts
> +  console.log(wrapper);
If the wrapper is not guaranteed perhaps some conditional logging would be better to catch failed states? Not generally a fan `console.log` in clients - tends to get noisy with more debugs

2022-11-29 12:03 UTC, imndaiga commented on src/components/mount-auto-suggest.ts
> +  console.log(wrapper);
Looks like we already do this with the `getObserver`, so the above wouldn't be necessary if we wanted that logic and can remove the logging here I imagine

2022-11-29 12:14 UTC, imndaiga commented on src/utils/noop.ts
> +export function noop() {}
Might be good to raise a `MissingHandler` warning or something?

2022-11-29 15:42 UTC, electather commented on src/components/mount-auto-suggest.ts
> +  console.log(wrapper);
this is just leftover from development, deleted in future branches.

2022-11-29 15:44 UTC, electather commented on src/utils/noop.ts
> +export function noop() {}
this is just used as default to prevent calling null as a function when passed as an option. also we don't have any logger for 3rd party websites to keep the script bundle size minimal.

2022-11-30 11:09 UTC, chaddgrimm approved these changes

2022-11-30 11:22 UTC, c5haw approved these changes
Just one comment regarding documenting the scripts in a README to clarify what each `compile` vs `build` should be used for, but otherwise all good

2022-11-30 11:22 UTC, c5haw commented on package.json
> +    "build": "VERSION=$npm_package_version webpack --config webpack.prod.js",
I'd probably add this to the README so it's clear which each is useful for for new contributors.

2022-11-30 12:07 UTC, merged