[IN-112]: add deployment step
w3w-internal/bigcommerce-storefront-plugin pull request #2
Opened 2022-11-28 11:40 UTC by electather

# Description

## What is the motivation for this pull request?

This PR adds required configurations for Circle CI to run test, build and deploy for the plugin. 

## What is the solution?

N/A

## What areas of the site does it impact?

Build and deploy

## How to test?

- [ ] Build and deploy 

## Other Notes

N/A

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-11-28 12:11 UTC, c5haw reviewed
Are there some missing files from the commit?

2022-11-28 12:11 UTC, c5haw commented on .circleci/config.yml
> +      - run: npm run build
```suggestion
      - run: npm run compile
```
Accidental change?

2022-11-28 14:53 UTC, electather commented on .circleci/config.yml
> +      - run: npm run build
no, in this case, [we need the `build` script to be run](https://github.com/w3w-internal/bigcommerce-storefront-plugin/blob/1e4aa254fcfdab7f67678ecf4d2ffcbe9d17449d/package.json#L29).
This PR builds upon #1  but it's not merged yet.

2022-11-30 13:26 UTC, c5haw requested changes
I like the gitops approach of using Github Releases (and tags) to trigger deployments. This aligns with what I was envisioning for triggering publishing libraries/plugins. If we are going to go down this approach though I think theres a few things think you should do here some of which should be discussed and potentially replicated into the library boilerplate/libraries elsewhere:

1. Use semantic versioning when we create a release/tag
2. Following semver we should use the [prelease semantic](https://github.com/npm/node-semver#functions) as the trigger for dev CDN so `/^(?:[0-9]+\.){2}\.[0-9]+-alpha\.[0-9]+$/` (and without prerelease tag for production)

I have an example of this [here](https://github.com/w3w-internal/javascript-sdk/pull/60/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R179-R273) that triggers publishing prerelease or latest depending on the version regex test using circleci `when...unless` conditionals. Might inspire something here (and other projects/boilerplate)
3. Setting the version env var to use the tag first or fallback to the version in `package.json`
  `echo "export VERSION=${CIRCLE_TAG:-$(cat << parameters.version_path >>/package.json | grep '\"version\":' | sed -e 's/ \"version\": \"//' | sed -e 's/\",//')}" >> $BASH_ENV`
4. Naming convention; for libraries I tend to use the terminology publish rather than deploy
5. Remove preprod CDN as this doesn't exist and just replicates dev

2022-11-30 13:26 UTC, c5haw commented on .circleci/config.yml
> +      - setup_environment
```suggestion
```

2022-11-30 13:26 UTC, c5haw commented on .circleci/config.yml
> +          arguments: --delete
Remove this block as its redundant.

2022-11-30 13:26 UTC, c5haw commented on .circleci/config.yml
>    tag:
Remove this job

2022-11-30 15:08 UTC, electather commented on .circleci/config.yml
> +      - run: npm run build
the main is (was) just boilerplate, and #1 had nothing to do with the deployment step. this was done to reduce the dependency of the PRs on each other, so they can be merged independently.

2022-11-30 15:25 UTC, electather commented on .circleci/config.yml
>    tag:
This is the deployment step for prod. do you have any replacements in mind?

2022-11-30 15:38 UTC, electather commented
@c5haw I updated the deployment with my spin on the regex. have a look.

2022-12-01 09:38 UTC, c5haw commented on .circleci/config.yml
>    tag:
It highlighted the wrong line. This was meant to be highlighting the `tag` job

2022-12-01 09:51 UTC, c5haw requested changes
One other question. The way this writes to s3 means that you can only ever have a single version published at any time. Do we want to be able to point to a specific version at any point? Something like:

```
        aws-s3/sync:
          from: /tmp/workspace/build/
          to: 's3://<< pipeline.parameters.dev-s3-bucket >>/bigcommerce-storefront-plugin@<< parameters.version >>/'
          arguments: --delete
```

And pass in the version taken from the `VERSION` env var set in `setup_environment`

2022-12-01 09:51 UTC, c5haw commented on .circleci/config.yml
> +      only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9]+)*))?(?:\+[0-9]+)?$/
```suggestion
      only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9]+)*)){1}(?:\+[0-9]+)?$/
```
If this is only prerelease then I presume it should have the prerelease suffix

2022-12-01 09:51 UTC, c5haw commented on .circleci/config.yml
>        - setup_environment
```suggestion
```
Can remove this job as the env vars that are set there are not being used anywhere.

2022-12-01 09:51 UTC, c5haw commented on .circleci/config.yml
> +          version_path: /tmp/workspace/
```suggestion
```
Can remove this job as the env vars that are set there are not being used anywhere.

2022-12-01 09:51 UTC, c5haw commented on .circleci/config.yml
> +          version_path: /tmp/workspace/
```suggestion
```
Can remove this job as the env vars that are set there are not being used anywhere.

2022-12-01 10:49 UTC, c5haw approved these changes
Still one outstanding question but it'll come up again at a later date and we can address then - LGTM

2022-12-02 10:23 UTC, electather commented
@c5haw I didn't see this question:
> One other question. The way this writes to s3 means that you can only ever have a single version published at any time. Do we want to be able to point to a specific version at any point? Something like:

having multiple versions doesn't really do anything for us, in case of ecwid, the process of changing version is time consuming by ecwid, and it's done once for everyone, users can't really pick their versions, it's always gonna be latest. 
as for development / beta application, we have that, in a form of dev S3 bucket. 
as for bigcommerce, we can deploy different versions, but then managing deployed scripts and bumping script versions for our users ( per user basis ) is gonna be a challange. 
so in my mind, best way to go is with reproducable buids, just running an older tag's job in circle CI will overwrite the exisiting versions. so we don't have to keep diffrent versions on our bucket.

2022-12-02 10:23 UTC, merged